PREFIX ex: <http://example.com/>

SELECT * WHERE {
  ?comment ex:creator ex:user;
    ex:content ?content;
    ex:reply ?message.
  ?message ex:hasTopic ?topic;
    ex:forum ?forum.
  ?forum ex:name ?name.
}